// Quranic verses in the khutbah — shown ONLY from approved sources (challenge science package):
// mushaf text of the King Fahd Complex (KFGQPC Uthmanic Hafs v13) + published translations of meanings.
// Nothing about a verse is generated by a model. See SOURCES.md.
const Q = "assets/quran/";
const TASH = /[ؐ-ًؚ-ٰٟۖ-ࣰۭ-ࣲـ]/g;
export function qnorm(s) {
  return s.replace(TASH, "").replace(/[إأآٱ]/g, "ا").replace(/ى/g, "ي").replace(/ة/g, "ه").replace(/ؤ/g, "و").replace(/ئ/g, "ي")
    .replace(/[^ء-ي\s]/g, " ").replace(/\s+/g, " ").trim();
}
const AR = "٠١٢٣٤٥٦٧٨٩";
export const arNum = n => String(n).replace(/\d/g, d => AR[+d]);

let idxP = null;
export function loadQuranIndex() {
  return (idxP ??= fetch(Q + "index.json").then(r => r.json()).then(d => {
    const words = [], sa = [], key = new Map(), sh = new Map();
    d.v.forEach(([s, a, t], i) => {
      const w = t.split(" ");
      words.push(w); sa.push([s, a]); key.set(s + ":" + a, i);
      for (let p = 0; p + 2 < w.length; p++) {
        const k = w[p] + " " + w[p + 1] + " " + w[p + 2], code = i * 512 + p;
        const L = sh.get(k); if (L) L.push(code); else sh.set(k, [code]);
      }
    });
    return { names: d.names, words, sa, key, sh };
  }));
}
const refOf = (ix, s, a) => `سورة ${ix.names[s - 1]} · ${arNum(a)}`;

const CUE = /قال\s*(الله\s*)?تعالى|قال\s+الله|يقول\s+(الله|ربنا|سبحانه)|قوله\s+تعالى|عز\s+وجل|جل\s+(وعلا|جلاله)|في\s+محكم|سبحانه\s+يقول|﴿|﴾/;
function hasCue(text) {
  const letters = (text.match(/[ء-ي]/g) || []).length;
  const marks = (text.match(TASH) || []).length;
  return CUE.test(text) || (letters > 8 && marks / letters > 0.45);
}

export async function findAyat(text, cue = false) {
  const ix = await loadQuranIndex();
  const w = qnorm(text).split(" ").filter(Boolean);
  if (w.length < 3) return [];
  const cued = cue || hasCue(text);
  const minWords = cued ? 3 : 6;
  const runs = new Map();
  for (let i = 0; i + 2 < w.length; i++) {
    const hits = ix.sh.get(w[i] + " " + w[i + 1] + " " + w[i + 2]);
    if (!hits || hits.length > 400) continue;
    for (const code of hits) {
      const v = Math.floor(code / 512), p = code % 512, k = v + "|" + (p - i);
      let S = runs.get(k); if (!S) runs.set(k, (S = new Set()));
      S.add(i); S.add(i + 1); S.add(i + 2);
    }
  }
  const cands = [...runs.entries()].map(([k, S]) => ({ v: +k.split("|")[0], S })).sort((x, y) => y.S.size - x.S.size || x.v - y.v);
  const used = new Set(), out = [];
  for (const c of cands) {
    const fresh = [...c.S].filter(i => !used.has(i));
    if (fresh.length < minWords) continue;
    const cover = c.S.size / ix.words[c.v].length;
    const isWhole = cued && c.S.size >= Math.max(3, w.length - 2);
    if (cover < 0.5 && c.S.size < 6 && !isWhole) continue;
    const also = cands.filter(o => o !== c && o.S.size === c.S.size && [...o.S].every(i => c.S.has(i))).map(o => ix.sa[o.v]);
    c.S.forEach(i => used.add(i));
    const [s, a] = ix.sa[c.v];
    out.push({ s, a, partial: cover < 0.85, also: also.filter(([s2, a2]) => s2 !== s || a2 !== a).slice(0, 4), at: Math.min(...c.S) });
    if (out.length >= 4) break;
  }
  return out.sort((x, y) => x.at - y.at);
}

const surahP = new Map();
const surah = s => {
  if (!surahP.has(s)) surahP.set(s, fetch(Q + `s/${String(s).padStart(3, "0")}.json`).then(r => r.json()));
  return surahP.get(s);
};

/** verified verses in a sentence: [{s, a, ref, t (official text), m (التفسير الميسر, internal), partial, also}] */
export async function versesIn(text, cue = false) {
  try {
    const found = await findAyat(text, cue);
    if (!found.length) return [];
    const ix = await loadQuranIndex();
    return Promise.all(found.map(async f => {
      const x = (await surah(f.s)).ayat[f.a - 1];
      return { s: f.s, a: f.a, ref: refOf(ix, f.s, f.a), t: x.t, m: x.m, partial: f.partial, also: f.also.length ? f.also.map(([s, a]) => refOf(ix, s, a)) : null };
    }));
  } catch { return []; }
}

const trP = new Map();
/** published translation of meanings (never machine translation) */
export async function ayahTranslation(lang, s, a) {
  if (!trP.has(lang)) trP.set(lang, fetch(Q + `tr/${lang}.json`).then(r => { if (!r.ok) throw 0; return r.json(); }));
  try {
    const [ix, T] = await Promise.all([loadQuranIndex(), trP.get(lang)]);
    const i = ix.key.get(s + ":" + a);
    return i === undefined ? null : { text: T.v[i], source: T.source };
  } catch { return null; }
}

// Amiri Quran renders the KFGQPC v13 marks (open tanween…) correctly
if (typeof document !== "undefined" && !document.getElementById("quran-font")) {
  const st = document.createElement("style"); st.id = "quran-font";
  st.textContent = `@font-face{font-family:"Amiri Quran";font-display:swap;src:url(assets/fonts/amiri-quran.woff2) format("woff2")}`;
  document.head.appendChild(st);
}
